# Site Configuration
title: "Bryce Westheimer"
description: "Theoretical chemistry and applied mathematics researcher advancing computational modeling, optimization, and numerical analysis for fragment-based quantum chemistry"
url: "https://brycewestheimer.github.io"
baseurl: ""

# Author Information
author:
  name: "Bryce Westheimer"
  title: "Postdoctoral Research Associate, University of Colorado, Denver"
  bio: "Theoretical chemist and applied mathematician focused on computational modeling, optimization, and numerical analysis for fragment-based quantum chemistry and accelerator-ready scientific software."
  location: "Vancouver, WA"
  email: "brycemwestheimer@gmail.com"
  github: "brycewestheimer"
  linkedin: "bryce-westheimer"
  google_scholar: "gnELDysAAAAJ"
  avatar: "/assets/profile_image.jpg"

# Site Settings
layout: sidebar
style: auto  # Matches system theme preference
timezone: America/Los_Angeles

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

permalink: /:year/:month/:day/:title/

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:name/

# SEO Settings
lang: en_US
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Bryce Westheimer"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "post"
      author: "Bryce Westheimer"
      category: "tutorial"

# Project Settings
projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      # Add any repos you want to exclude

# Navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Research"
    url: "/research/"
  - name: "Projects"
    url: "/projects/"
  - name: "Publications"
    url: "/publications/"
  - name: "Blog"
    url: "/blog/"
  - name: "Tutorials"
    url: "/tutorials/"
  - name: "Contact"
    url: "/contact/"

# Social Media Configuration
social_media:
  github: brycewestheimer
  linkedin: bryce-westheimer
  google_scholar: gnELDysAAAAJ
  email: brycemwestheimer@gmail.com

# Research Topics & Expertise
topics:
  - name: "Fragment-Based Quantum Chemistry"
    description: "Subsystem-local SAPT, covalent fragment coupling, and MAP-enabled workflows for chemically realistic systems."
    web_url: "/research/"
    link_label: "Explore research"
  - name: "Multi-layer Adaptive Partitioning (MAP)"
    description: "Hierarchical partitioning strategies and analysis tooling that balance accuracy and scalability."
    web_url: "/projects/"
    link_label: "See MAP tooling"
  - name: "Accelerator-Ready Electronic Structure"
    description: "Optimizing GAMESS-derived kernels for heterogeneous CPU/GPU architectures and DOE-class platforms."
    web_url: "/projects/"
    link_label: "View accelerator work"
  - name: "Open Scientific Software"
    description: "Maintaining collaborative, open-source infrastructure that helps labs adopt fragment-based methods."
    web_url: "/projects/"
    link_label: "Browse repositories"

# Skills & Technologies
skills:
  languages:
    - "Python"
    - "C++"
    - "C"
    - "R"
    - "SQL"
    - "Fortran"
    - "CUDA"
    - "MPI/OpenMP"
  frameworks:
    - "GAMESS"
    - "Psi4"
    - "PySCF"
    - "libfrag"
    - "TensorFlow Probability"
    - "PyTorch"
    - "JAX"
    - "CMake"
  tools:
    - "Git"
    - "GitHub Actions"
    - "Conda/Mamba"
    - "Spack"
    - "Docker"
    - "Apptainer"
    - "SLURM"
    - "NVIDIA HPC SDK"
    - "Intel oneAPI"

# Key Projects (upcoming)
featured_projects:
  - name: "libfrag"
    status: "Active development"
    description: "Fragment-based quantum chemistry sandbox for MAP prototypes and subsystem analyses."
    tech: "Python · C++ · CMake"
    url: "https://github.com/brycewestheimer/libfrag"
  - name: "public_libaccefp"
    status: "Public preview"
    description: "GPU-aware effective fragment potential kernels shared for community benchmarking."
    tech: "C++ · CUDA · Fortran"
    url: "https://github.com/brycewestheimer/libaccefp"
  - name: "public_libaccsapt"
    status: "Preview"
    description: "Subsystem-local SAPT acceleration modules aligned with ACS Fall 2024 highlights."
    tech: "C++ · OpenMP · MPI"
    url: "https://github.com/brycewestheimer/libaccsapt"
  - name: "public_qccg"
    status: "In development"
    description: "Template-driven kernel generator supporting quantum chemistry code modernization."
    tech: "C++ · Python"
    url: "https://github.com/brycewestheimer/qccg"
