# Site Configuration
title: "Bryce Westheimer"
description: "Postdoctoral Fellow specializing in quantum chemistry method development and high-performance computing applications"
url: "https://brycewestheimer.github.io"
baseurl: ""

# Author Information
author:
  name: "Bryce Westheimer"
  bio: "Quantum chemistry researcher developing scalable computational methods for industry applications"
  location: "Vancouver, WA (Remote)"
  email: "westheb@gmail.com"  # Update with your actual email
  github: "brycewestheimer"
  linkedin: "bryce-westheimer"  # Update with your LinkedIn username
  google_scholar: "gnELDysAAAAJ"  # Your Google Scholar ID from the search
  avatar: "/assets/profile.jpg"  # Add your professional photo here

# Site Settings
layout: sidebar
style: auto  # Matches system theme preference
timezone: America/Los_Angeles

plugins:
  - jekyll-octicons
  # - jekyll-github-metadata  # Temporarily disabled for local testing
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

permalink: /:year/:month/:day/:title/

# SEO Settings
lang: en_US
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Bryce Westheimer"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Project Settings
projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
      # Add any repos you want to exclude

# Navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Research"
    url: "/research/"
  - name: "Projects"
    url: "/projects/"
  - name: "Publications"
    url: "/publications/"
  - name: "Blog"
    url: "/blog/"
  - name: "Tutorials"
    url: "/tutorials/"
  - name: "Contact"
    url: "/contact/"

# Social Media Configuration
social_media:
  linkedin: bryce-westheimer  # Update with your actual LinkedIn username
  github: brycewestheimer
  google_scholar: gnELDysAAAAJ
  email: westheb@gmail.com  # Update with your actual email
  # Add other social media as needed

# Research Topics & Expertise
topics:
  - name: "Quantum Chemistry Method Development"
    description: "Ab initio fragmentation methods and scalable quantum chemistry algorithms"
    web_url: "https://scholar.google.com/citations?user=gnELDysAAAAJ"
    image_url: "/assets/images/quantum-chemistry.svg"
    
  - name: "High-Performance Computing"
    description: "Optimization of quantum chemistry software for novel computer architectures"
    web_url: "https://scholar.google.com/citations?user=gnELDysAAAAJ"
    image_url: "/assets/images/hpc.svg"
    
  - name: "QM/MM Methods"
    description: "Mixed quantum mechanics/molecular mechanics simulation techniques"
    web_url: "https://scholar.google.com/citations?user=gnELDysAAAAJ"
    image_url: "/assets/images/qmmm.svg"
    
  - name: "Computational Chemistry Software"
    description: "Development and optimization of scientific computing applications"
    web_url: "https://scholar.google.com/citations?user=gnELDysAAAAJ"
    image_url: "/assets/images/software.svg"

# Skills & Technologies
skills:
  languages:
    - "Fortran"
    - "C/C++"
    - "Python"
    - "CUDA"
    - "OpenMP"
    - "MPI"
  frameworks:
    - "GAMESS"
    - "NumPy/SciPy"
    - "PyTorch/TensorFlow"
    - "Jupyter"
  tools:
    - "Git"
    - "CMake"
    - "Docker"
    - "SLURM"
    - "Intel Compilers"
    - "NVIDIA HPC SDK"

# Key Projects (upcoming)
featured_projects:
  - name: "PyFrag"
    description: "Python-based fragmentation analysis toolkit"
    status: "In Development"
    
  - name: "LibAccInt"
    description: "Accurate integration library for quantum chemistry"
    status: "In Development"
    
  - name: "MAP-QM/MM"
    description: "Massively parallel QM/MM simulation framework"
    status: "In Development"
